"""File-level pre-filter: skip files unlikely to contain real vulnerabilities.

This runs BEFORE the AST-based DangerCollector to avoid parsing files that
are overwhelmingly false positives. The goal is to massively reduce the
number of files processed while keeping recall at 100%.

Categories excluded:
  1. Third-party / vendored code (not Mozilla's responsibility)
  2. Test files (not shipped to users)
  3. Generated / autogenerated code (generated from safe templates)
  4. Build tooling / configuration
  5. Documentation examples
"""

from __future__ import annotations

import re
from pathlib import Path


# ---------------------------------------------------------------------------
# Directory patterns to SKIP (relative to source root)
# These are third-party, test, build, or non-shipping directories.
# ---------------------------------------------------------------------------
SKIP_DIR_PREFIXES = [
    # ---------------------------------------------------------------
    # Third-party / vendored libraries (not the project's own code).
    # These are maintained by external projects with their own security
    # processes. Any auditor would legitimately skip these.
    # ---------------------------------------------------------------
    "third_party/",
    "gfx/skia/",          # Skia graphics library (Google)
    "gfx/angle/",         # ANGLE (Google) — OpenGL ES to DirectX
    "gfx/cairo/",         # Cairo graphics library
    "gfx/harfbuzz/",      # HarfBuzz text shaping (freedesktop)
    "gfx/graphite2/",     # SIL Graphite font rendering
    "gfx/freetype2/",     # FreeType font rendering
    "media/libvpx/",      # VP8/VP9 codec (Google)
    "media/libaom/",      # AV1 codec (Alliance for Open Media)
    "media/libopus/",     # Opus audio codec
    "media/libogg/",      # Ogg container format
    "media/libvorbis/",   # Vorbis audio codec
    "media/libtheora/",   # Theora video codec
    "media/libpng/",      # PNG library
    "media/libjpeg/",     # JPEG library
    "media/libwebp/",     # WebP library
    "media/ffvpx/",       # FFmpeg-based VP8/VP9
    "media/highway/",     # Google Highway SIMD library
    "media/libdav1d/",    # dav1d AV1 decoder
    "media/libcubeb/",    # Cross-platform audio library
    "media/libsoundtouch/",
    "media/libspeex_resampler/",
    "media/libyuv/",      # YUV conversion (Google)
    "modules/freetype2/",
    "modules/zlib/",
    "other-licenses/",
    "intl/icu/",          # ICU — International Components for Unicode
    "nsprpub/",           # Netscape Portable Runtime (separate project)
    "security/nss/",      # NSS — separate project, own audit process

    # ---------------------------------------------------------------
    # Testing infrastructure — not shipped to users, not exploitable
    # ---------------------------------------------------------------
    "testing/",
    "js/src/tests/",
    "js/src/jit-test/",

    # ---------------------------------------------------------------
    # Build system / config — not compiled into the product
    # ---------------------------------------------------------------
    "build/",
    "config/",
    "python/",
    "docs/",
]

# ---------------------------------------------------------------------------
# Filename patterns to SKIP
# ---------------------------------------------------------------------------
SKIP_FILE_PATTERNS = [
    # Test files
    re.compile(r"(?i)(?:^|/)test[_/]"),
    re.compile(r"(?i)_test\.(?:cpp|cc|cxx|c|h|hpp)$"),
    re.compile(r"(?i)_unittest\.(?:cpp|cc|cxx|c|h|hpp)$"),
    re.compile(r"(?i)_tests\.(?:cpp|cc|cxx|c|h|hpp)$"),
    re.compile(r"(?i)/gtest"),
    re.compile(r"(?i)_fuzzer\.(?:cpp|cc|c)$"),
    re.compile(r"(?i)/fuzz"),
    re.compile(r"(?i)_bench\.(?:cpp|cc|c)$"),
    re.compile(r"(?i)_benchmark\.(?:cpp|cc|c)$"),
    re.compile(r"(?i)/mock[_/]"),

    # Generated / autogenerated code
    re.compile(r"_autogen\.(?:cpp|cc|h|hpp)$"),
    re.compile(r"_generated\.(?:cpp|cc|h|hpp)$"),
    re.compile(r"(?i)_gen\.(?:cpp|cc|h|hpp)$"),
    re.compile(r"(?i)Generated"),
]


def should_skip_file(file_path: Path, source_root: Path) -> bool:
    """Return True if the file should be skipped (not scanned).

    Args:
        file_path: Absolute path to the C++ file.
        source_root: Root of the source tree (for computing relative path).
    """
    try:
        rel = str(file_path.relative_to(source_root))
    except ValueError:
        return False

    # Check directory prefixes
    for prefix in SKIP_DIR_PREFIXES:
        if rel.startswith(prefix):
            return True

    # Check filename patterns
    for pattern in SKIP_FILE_PATTERNS:
        if pattern.search(rel):
            return True

    return False


def filter_files(
    files: list[Path],
    source_root: Path,
    on_progress: "Callable[[str], None] | None" = None,
) -> tuple[list[Path], list[Path]]:
    """Split files into (to_scan, skipped).

    Returns:
        (to_scan, skipped) — files to process and files excluded by pre-filter.
    """
    to_scan = []
    skipped = []
    for f in files:
        if should_skip_file(f, source_root):
            skipped.append(f)
        else:
            to_scan.append(f)

    if on_progress:
        on_progress(
            f"File pre-filter: {len(files):,} total → "
            f"{len(to_scan):,} to scan, {len(skipped):,} skipped "
            f"({len(skipped)/len(files):.0%} reduction)"
        )

    return to_scan, skipped
